### ISSUE TITLE
removeSeries fails with Value is undefined during unmount event

### ISSUE THREAD

**Issue by thomasnal** [tradingview/lightweight-charts#1454]
Hi,

In React app, we have a hook that creates a line series and displays the data when the chart element and data becomes available.  The code is included below.  The code works as expected to display new data and when data changes, an existing series gets removed and a new series with new data gets created.

There is however a crash in lightweight-charts (LWC) when the code calls `removeSeries` at component unmount time, that is when the HTML element is getting removed from the page.  The `removeSeries` at the unmount time crashes failing to find series in its internal structure.

The code is well isolated and should be easy to understand.  Additional debug shows the `studiesSeries` array contains the series as expected.  The `removeSeries` should be able to complete with success the same way as in the cases when data changes. 

**Lightweight Charts™ Version:** 3.8.0

**Steps/code to reproduce:**

```js
export default function useDisplayStudies(
  chart: IChartApi,
  studies: DataPoint[][]): void
{
  useEffect(() => {
    const studiesSeries = [];

    studies.forEach((study, idx) => {
      if (study.length > 0) {
        const series = chart.addLineSeries(studiesStyles[idx]);
        studiesSeries.push(series);
        series.setData(study);
      }
    })

    return () => {
      studiesSeries.forEach((series) => {
        chart.removeSeries(series);
      });
    };
  }, [chart, studies]);

  return;
}
```

**Actual behavior:**
In React, useEffect hook gets called when `chart` element or `studies` data change.  Additionally, it gets called at unmount time when the component is removed.  When the data changes the code works as expected. At the unmount time, however, `removeSeries` crashes with the following error,
```
Uncaught Error: Value is undefined
    at e (lightweight-charts.esm.production.js:7:1)
    at t.removeSeries (lightweight-charts.esm.production.js:7:1)
    at useDisplayStudies.ts:39:1
    at Array.forEach (<anonymous>)
    at useDisplayStudies.ts:38:1
    at safelyCallDestroy (react-dom.development.js:22932:1)
    at commitHookEffectListUnmount (react-dom.development.js:23100:1)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (react-dom.development.js:25098:1)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (react-dom.development.js:25048:1)
    at commitPassiveUnmountEffects_begin (react-dom.development.js:24956:1)
    at commitPassiveUnmountEffects (react-dom.development.js:24941:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27038:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at commitRootImpl (react-dom.development.js:26935:1)
    at commitRoot (react-dom.development.js:26682:1)
    at performSyncWorkOnRoot (react-dom.development.js:26117:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
    at react-dom.development.js:25651:1
```
The `chart` suddenly does not contain the series and crashes calling `removeSeries`.  Debug shows that the `chart` and `series` values are valid objects.  The `chart.remove()` has not been called yet - part of another hook.

**Expected behavior:**
Call to `removeSeries` will complete with success at the event of unmounting the component from the view.

**Comment by thomasnal** [comment]
I double checked `chart.remove()` and react calls that first before this hook.
