### ISSUE TITLE
Support OKLCH color space

### ISSUE THREAD

**Issue by benphelps** [tradingview/lightweight-charts#1475]
**Lightweight Charts™ Version:** 4.0.1, 4.1.1

The OKLCH color space has recently been introduced into all modern browsers, and while the colors work in some places, some places they do not.  Here is one example of such a place.

**Steps/code to reproduce:**

```js
var series = chart.addAreaSeries({
  topColor: 'oklch(0.6569 0.196 275.75)', // this is fine
  bottomColor: 'rgba(0, 150, 136, 0.04)',
  lineColor: 'oklch(0.6569 0.196 275.75)', // this is NOT fine
  lineWidth: 2,
});
```

**Actual behavior:**

```
Uncaught Error: Cannot parse color: oklch(0.6569 0.196 275.75)
    at colorStringToRgba ...
```

**Expected behavior:**

Handle the new OKLCH color space everywhere.

`colorStringToRgba` in `src/helpers/color.ts` seems to be where the conversion is done.

Here is a fork adding support, however since I have no knowledge around color spaces, the conversion code is directly from ChatGPT, and I don't feel comfortable submitting that as a PR.  I have tested it with a few colors, comparing to the values given by https://oklch.com/ and it does seem to function correctly, even for values outside of the RGB color space.

https://github.com/benphelps/lightweight-charts/tree/oklch

**CodeSandbox/JSFiddle/etc link:**

https://jsfiddle.net/ykpg8v7c/

**Comment by SlicedSilver** [comment]
Thanks for raising this issue @benphelps. 

Converting oklch colours into RGB would add support to the library for the colour syntax but it wouldn't allow the support of actually displaying the expanded colour palette (such as P3 colours).

I'll adding this issue to our milestone for an upcoming release so we will have a look at implementing this support but I wouldn't expect it to land in a released version within the near future. In the meantime, you could handle the conversion outside of the library, and only provide the rgb strings to the library.

**Comment by SlicedSilver** [comment]
Expanded support for color syntax was introduced in version 5.
https://tradingview.github.io/lightweight-charts/docs/release-notes#500

**Comment by joeblau** [comment]
There isa bug in this code where downColor on `chart.addSeries(CandlestickSeries` throws an error when trying to process oklch colors.

```
Error: Failed to parse color: oklch(0.67 0.31 357)
    at ColorParser._private__parseColor (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:463:19)
    at ColorParser._internal_generateContrastColors (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:426:27)
    at SeriesPriceAxisView._internal__updateRendererData (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:2168:88)
    at SeriesPriceAxisView._private__updateRendererDataIfNeeded (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:1045:18)
    at SeriesPriceAxisView._internal_text (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:997:14)
    at PriceAxisWidget._internal_optimalWidth (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:8200:89)
    at PriceAxisWidget._private__onMarksChanged (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:8536:28)
    at http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:204:56
    at Array.forEach (<anonymous>)
    at Delegate._internal_fire (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:204:27)
    at PriceScale._internal_marks (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:4267:39)
    at PriceAxisWidget._internal_optimalWidth (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:8193:53)
    at ChartWidget._private__adjustSizeImpl (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:10009:128)
    at ChartWidget._private__syncGuiWithModel (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:10254:14)
    at ChartWidget._private__updateGui (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:10207:14)
    at ChartWidget._private__drawImpl (http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:10118:18)
    at http://localhost:3000/_next/static/chunks/node_modules_lightweight-charts_dist_lightweight-charts_development_mjs_d370ebd8._.js:10195:26
```

Should I create a new issue?

edit: looks like all higher order color spaces on colorDown aren't working. I just tried:  `color(display-p3 0.9978 0.2415 0.6189)` and it works on upColor, but not on downColor.

**Comment by illetid** [comment]
Hi @joeblau you need to provide color parser https://tradingview.github.io/lightweight-charts/docs/api/interfaces/LayoutOptions#colorparsers for the oklch to the library, as it is not included into the bundle by default to keep it as lightweight as possible. 
You can use something like https://colorjs.io/ or check for other alternatives

**Comment by joeblau** [comment]
This is my config rendering the chart. oklch works on every other field except upColor and downColor. it even works on gridLines and vertLines so I think there is a bug in the color parsing.

```
const candlestickSeries = chart.addSeries(CandlestickSeries, {
❌ upColor: '#00FF00', // fastjpeg green
❌ downColor: '#FF479C', // BUG: fastjpeg pink oklch(0.6971 0.2787 356.98)
// borderVisible: false,
✅ wickUpColor: 'oklch(0.8529 0.3552 144.3458)', // fastjpeg green wick
✅ wickDownColor: 'oklch(0.6971 0.2787 356.98)', // fastjpeg pink
✅ borderUpColor: 'oklch(0.8529 0.3552 144.3458)', // fastjpeg green
✅ borderDownColor: 'oklch(0.6971 0.2787 356.98)', // fastjpeg pink
...
});
```

<img width="525" alt="Image" src="https://github.com/user-attachments/assets/1a46c277-3412-4cb6-9891-040d3a61965d" />

**Comment by illetid** [comment]
@joeblau  it's failing because library tries to parse up and down colors for things like generating contrast colors for price scale label text, and it can't parse `oklch` by default, to make it work you need to provide color parser https://tradingview.github.io/lightweight-charts/docs/api/interfaces/LayoutOptions#colorparsers for oklch

**Comment by SlicedSilver** [comment]
Here is an example for a different colour space (P3). https://github.com/tradingview/lightweight-charts/blob/master/tests/e2e/graphics/test-cases/color-p3-support.js

**Comment by MickL** [comment]
> Expanded support for color syntax was introduced in version 5. https://tradingview.github.io/lightweight-charts/docs/release-notes#500

Sorry I dont understand. You said expanded support was introduced, but then when I try it throws and error `Failed to parse color: oklch(55.4% 0.046 257.417)`. And there it says I need to add a color parser? 

I made it work using [color-rgba](https://github.com/colorjs/color-rgba) like this:

```ts
import rgba from 'color-rgba';
import { type ChartOptions } from 'lightweight-charts';

const chartOptions: DeepPartial<ChartOptions> = {
    layout: {
      colorParsers: [rgba],
    },
};
```

Maybe this snippet could be added to the docs?

**Comment by SlicedSilver** [comment]
Adding that example to the documentation will be helpful, most likely here (on the API reference): https://tradingview.github.io/lightweight-charts/docs/api/interfaces/LayoutOptions#colorparsers
