### ISSUE TITLE
Incorrect module syntax?  Issue loading the module in an Electron env

### ISSUE THREAD

**Issue by matortheeternal** [tradingview/lightweight-charts#562]
**Lightweight Charts Version:** 3.1.5

**Steps/code to reproduce:**

1. Create a new Electron application using Rollup.
2. Attempt to import lightweight-charts.

```js
import {createChart} from 'lightweight-charts';
```

**Actual behavior:**

```
Uncaught C:\dev\git\hephaestus\node_modules\lightweight-charts\dist\lightweight-charts.esm.development.js:7
import { bindToDevicePixelRatio } from 'fancy-canvas/coordinate-space';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:84:7)
    at createScript (vm.js:258:10)
    at Object.runInThisContext (vm.js:306:10)
    at Module._compile (internal/modules/cjs/loader.js:884:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
```

**Expected behavior:**

Should load the module without error.

**Notes:**

I was able to work around this by patching `index.js` to load the standalone versions instead:

```js
'use strict';

if (process.env.NODE_ENV === 'production') {
	module.exports = require('./dist/lightweight-charts.standalone.production.js');
} else {
	module.exports = require('./dist/lightweight-charts.standalone.development.js');
}
```

This is a monkey-patch and obviously not ideal.  I've read in some places that this can be resolved by changing the file extension from .js to .mjs.  Adding "type": "module" to the `package.json` didn't seem to fix anything, probably have to do that as well as changing the extension to `mjs`.

```
node -v
v13.7.0
```

**Comment by timocov** [comment]
Hey, do you try to load it in nodejs env instead of browser's one? Quite probably "esm" syntax isn't correct (but that's what rollup generates).

**Comment by souliscrap** [comment]
Im quite stuck here. After patching index.js to load in the standalone versions im getting this error:

Uncaught TypeError: LightweightCharts.createChart is not a function
    at Object.<anonymous> (app\ChartRenderer.js:29)
    at Object.<anonymous> (app\ChartRenderer.js:206)
    at Module._compile (internal/modules/cjs/loader.js:1145)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166)
    at Module.load (internal/modules/cjs/loader.js:981)
    at Module._load (internal/modules/cjs/loader.js:881)
    at Function.Module._load (electron/js2c/asar.js:769)
    at Module.require (internal/modules/cjs/loader.js:1023)
    at require (internal/modules/cjs/helpers.js:77)
    at ChartPage.html:13

Same error when also I dynamically load the module.

Am I doing something wrong?

**Comment by souliscrap** [comment]
@timocov yes that's right

**Comment by timocov** [comment]
@souliscrap see https://github.com/tradingview/lightweight-charts/issues/543#issuecomment-686421467
