### ISSUE TITLE
lightweight-charts - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by souliscrap** [tradingview/lightweight-charts#595]
When loading in the lightweight charts module im getting an import/module error:

vm.js:96 Uncaught .\.\node_modules\lightweight-charts\dist\lightweight-charts.esm.development.js:7
import { bindToDevicePixelRatio } from 'fancy-canvas/coordinate-space';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:88:7)
    at createScript (vm.js:263:10)
    at Object.runInThisContext (vm.js:311:10)
    at wrapSafe (internal/modules/cjs/loader.js:1038:15)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)

Im using Electron and Node.js:
node 12.16.3
Chrome 85.0.4183.121
Electron 10.1.3

 tsconfig.json:
{
  "compilerOptions": {

    "target": "ES6",
    "module": "commonjs",
    "lib": ["es6", "DOM"],
    "allowJs": true,
    "outDir": "app",
    "rootDir": "src",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}

**Comment by timocov** [comment]
It seems that you're trying to use the library in NodeJS context (not in the browser's one)?

**Comment by timocov** [comment]
See #543, #562
