### ISSUE TITLE
TypeError: Cannot read property 'getContext' of null

### ISSUE THREAD

**Issue by ololoepepe** [tradingview/lightweight-charts#638]
**Lightweight Charts Version:** 3.2.0

**Steps/code to reproduce:**

```js
useEffect(() => {
  const c = createChart(chartRef.current, {
    // options
  });

  // other initialization

  return () => c.remove();
});
```

**Actual behavior:**

Exception is thrown:

```
TypeError: Cannot read property 'getContext' of null
  at vB(webpack://frontend/./node_modules/lightweight-charts/dist/lightweight-charts.esm.production.js:7:85788)
  at $c(webpack://frontend/./node_modules/lightweight-charts/dist/lightweight-charts.esm.production.js:7:112215)
  at $c(webpack://frontend/./node_modules/lightweight-charts/dist/lightweight-charts.esm.production.js:7:117214)
  at S_(webpack://frontend/./node_modules/lightweight-charts/dist/lightweight-charts.esm.production.js:7:119795)
  at apply(webpack://frontend/./node_modules/lightweight-charts/dist/lightweight-charts.esm.production.js:7:120143)
  at r(webpack://frontend/./node_modules/@sentry/browser/esm/helpers.js:72:23)
```

Note: I am aware of https://github.com/tradingview/lightweight-charts/issues/248, and `.remove()` is used.

**Expected behavior:**

Expected no exception.

**Screenshots:**

No screenshots to provide.

**CodeSandbox/JSFiddle/etc link:**

Was not able to reproduce myself. Only 1 user is experiencing this issue (Chrome 86.0.4240, Windows 10). About 30 times this month.

**Comment by timocov** [comment]
I'm afraid without a reproduction we can't even try to solve this issue - all I see in the code that `getContext` is called from canvas elements what means that perhaps `document.createElement('canvas')` returned `null` what is against the spec.

**Comment by timocov** [comment]
I'm going to close the issue. If you'll have any question or updates - feel free to re-open it.
